(function(){
  window.TsukiyomiDailyItemOracleCards = [
    {
      id: 'item_001',
      shuku: '昴宿',
      type: '導きの月タイプ',
      cardName: '鏡のカード',
      item: '鏡',
      keyword: '本来の輝きを映す',
      message: '鏡は、今のあなたを責めるためではなく、本来の輝きを思い出すための道具です。',
      action: '鏡をやさしく拭き、今日の自分に「ここから整えていきます」と伝えましょう。',
      question: '今日の私は、どんな表情で一日を始めたいですか。',
      gratitude: 'いつも今の私を映してくれてありがとう。',
      image: 'images/oracle/item_001.png'
    },
    {
      id: 'item_002',
      shuku: '畢宿',
      type: '表現の月タイプ',
      cardName: '歯ブラシのカード',
      item: '歯ブラシ',
      keyword: '言葉の入口を清める',
      message: '歯磨きは、言葉の入口を整える小さな開運アクションです。',
      action: '歯を丁寧に磨きながら、今日届けたい言葉を一つだけ心に決めましょう。',
      question: '今日、私はどんな言葉を大切に扱いたいですか。',
      gratitude: '毎朝、言葉の入口を整えてくれてありがとう。',
      image: 'images/oracle/item_002.png'
    },
    {
      id: 'item_003',
      shuku: '觜宿',
      type: '変容の月タイプ',
      cardName: 'はさみのカード',
      item: 'はさみ',
      keyword: '余分な結び目をほどく',
      message: 'はさみは、乱れたものを切り離し、必要な形へ整える象徴です。',
      action: '不要な紙やタグを一つ整え、今日手放したい思いを短く書きましょう。',
      question: '今の私が、軽くするために整えたいことは何ですか。',
      gratitude: '必要な形に整える力をくれてありがとう。',
      image: 'images/oracle/item_003.png'
    },
    {
      id: 'item_004',
      shuku: '参宿',
      type: '導きの月タイプ',
      cardName: 'スニーカーのカード',
      item: 'スニーカー',
      keyword: '一歩踏み出す',
      message: 'スニーカーは、考えすぎた心を現実の一歩へ戻してくれる道具です。',
      action: '靴先を整え、今日は小さな用事を一つ前に進めましょう。',
      question: '今日の私が踏み出せる小さな一歩は何ですか。',
      gratitude: '私の一歩を支えてくれてありがとう。',
      image: 'images/oracle/item_004.png'
    },
    {
      id: 'item_005',
      shuku: '井宿',
      type: '癒しの月タイプ',
      cardName: 'グラスのカード',
      item: 'グラス',
      keyword: '心を澄ませる',
      message: 'グラスは、受け取る器を澄ませ、心の水面を静かに整えてくれます。',
      action: 'グラスを磨き、水やお茶を一口ゆっくり味わいましょう。',
      question: '今日の私の心を澄ませてくれるものは何ですか。',
      gratitude: '澄んだ時間を受け取らせてくれてありがとう。',
      image: 'images/oracle/item_005.png'
    },
    {
      id: 'item_006',
      shuku: '鬼宿',
      type: '変容の月タイプ',
      cardName: '石けんのカード',
      item: '石けん',
      keyword: '感情を洗い流す',
      message: '石けんは、心に残った違和感をやさしく洗い流す合図です。',
      action: '手を洗う時に、今日の疲れを水に流すイメージを持ちましょう。',
      question: '今日、私はどんな感情をやさしく流したいですか。',
      gratitude: '私を清らかな状態へ戻してくれてありがとう。',
      image: 'images/oracle/item_006.png'
    },
    {
      id: 'item_007',
      shuku: '柳宿',
      type: '癒しの月タイプ',
      cardName: 'ティッシュのカード',
      item: 'ティッシュ',
      keyword: '受け止めるやさしさ',
      message: 'ティッシュは、涙もこぼれたものも、日常の小さな乱れも受け止めてくれる存在です。',
      action: 'ティッシュを一枚手に取り、「いつも受け止めてくれてありがとう」と伝えましょう。',
      question: '今日、私がやさしく受け止めたい気持ちは何ですか。',
      gratitude: 'いつも受け止めてくれてありがとう。',
      image: 'images/oracle/item_007.png'
    },
    {
      id: 'item_008',
      shuku: '星宿',
      type: '表現の月タイプ',
      cardName: 'ポットのカード',
      item: 'ポット',
      keyword: '温めて注ぐ力',
      message: 'ポットは、内側で温めた思いを、必要な人へ注ぐ力を表します。',
      action: '温かい飲み物を淹れ、今の自分に必要な言葉を一つ書きましょう。',
      question: '私の中で温まり、そろそろ注ぎたい思いは何ですか。',
      gratitude: '温かな流れを運んでくれてありがとう。',
      image: 'images/oracle/item_008.png'
    },
    {
      id: 'item_009',
      shuku: '張宿',
      type: '表現の月タイプ',
      cardName: 'リップのカード',
      item: 'リップ',
      keyword: '伝える準備',
      message: 'リップは、言葉を届ける前に、自分の口元と心をやさしく整える道具です。',
      action: 'リップを塗り、今日やさしく伝えたい一言を決めましょう。',
      question: '今日、私はどんな言葉をやさしく届けたいですか。',
      gratitude: '言葉を届ける勇気を整えてくれてありがとう。',
      image: 'images/oracle/item_009.png'
    },
    {
      id: 'item_010',
      shuku: '翼宿',
      type: '表現の月タイプ',
      cardName: 'デスクライトのカード',
      item: 'デスクライト',
      keyword: '可能性を照らす',
      message: 'デスクライトは、考えや理想を手元まで照らし、形にするための灯りです。',
      action: 'デスクライトをつけて一つ作業を進め、終えたら静かに灯りを消しましょう。',
      question: '今日、私はどの可能性に光を当てたいですか。',
      gratitude: '私の手元と可能性を照らしてくれてありがとう。',
      image: 'images/oracle/item_010.png'
    },
    {
      id: 'item_011',
      shuku: '軫宿',
      type: '癒しの月タイプ',
      cardName: 'ペンのカード',
      item: 'ペン',
      keyword: '気づきを形に残す',
      message: 'ペンは、心に浮かんだ気づきを、あとから見返せる形に残してくれる道具です。',
      action: '今の気持ちを一行だけ書き、書いた自分に小さくうなずきましょう。',
      question: '今日の私が、形に残しておきたい気づきは何ですか。',
      gratitude: '見えない気持ちを形にしてくれてありがとう。',
      image: 'images/oracle/item_011.png'
    },
    {
      id: 'item_012',
      shuku: '角宿',
      type: '導きの月タイプ',
      cardName: '鍵のカード',
      item: '鍵',
      keyword: '次の扉を開く',
      message: '鍵は、守る場所と開く扉の両方を思い出させてくれる道具です。',
      action: '鍵を手に取り、今日開きたい小さな扉を一つ決めましょう。',
      question: '今の私が開きたい次の扉は何ですか。',
      gratitude: '大切な場所を守り、次の扉を開いてくれてありがとう。',
      image: 'images/oracle/item_012.png'
    },
    {
      id: 'item_013',
      shuku: '亢宿',
      type: '変容の月タイプ',
      cardName: '爪切りのカード',
      item: '爪切り',
      keyword: '先端を整える',
      message: '爪切りは、伸びすぎたものを整え、行動の先端を扱いやすくする道具です。',
      action: '爪や指先を整え、今日の行動を一つだけ軽くしましょう。',
      question: '今の私が、整えてから進みたいことは何ですか。',
      gratitude: '私の行動の先を整えてくれてありがとう。',
      image: 'images/oracle/item_013.png'
    },
    {
      id: 'item_014',
      shuku: '氐宿',
      type: '豊かさ循環タイプ',
      cardName: '財布のカード',
      item: '財布',
      keyword: '豊かさの入口',
      message: '財布は、お金だけでなく、受け取り方と送り出し方を映す道具です。',
      action: '財布の中を一つ整え、今日受け取っている豊かさを三つ思い出しましょう。',
      question: '今日、私がすでに受け取っている豊かさは何ですか。',
      gratitude: '豊かさの出入りを守ってくれてありがとう。',
      image: 'images/oracle/item_014.png'
    },
    {
      id: 'item_015',
      shuku: '房宿',
      type: '豊かさ循環タイプ',
      cardName: 'マグカップのカード',
      item: 'マグカップ',
      keyword: '満たされる時間',
      message: 'マグカップは、自分を満たす時間を日常の中に戻してくれる器です。',
      action: 'お気に入りの一杯を入れ、香りと温度をゆっくり受け取りましょう。',
      question: '今日の私を満たしてくれる時間は何ですか。',
      gratitude: '私を満たすひとときを受け止めてくれてありがとう。',
      image: 'images/oracle/item_015.png'
    },
    {
      id: 'item_016',
      shuku: '心宿',
      type: '表現の月タイプ',
      cardName: 'スマホのカード',
      item: 'スマホ',
      keyword: 'つながりの選び方',
      message: 'スマホは、誰とつながり、何を受け取るかを選ぶ日常の門です。',
      action: '通知を一つ整え、今日つながりたい人や情報を選び直しましょう。',
      question: '今の私にとって、心地よいつながり方は何ですか。',
      gratitude: '必要な人や情報とつないでくれてありがとう。',
      image: 'images/oracle/item_016.png'
    },
    {
      id: 'item_017',
      shuku: '尾宿',
      type: '変容の月タイプ',
      cardName: 'ゴミ袋のカード',
      item: 'ゴミ袋',
      keyword: '終わらせて空きを作る',
      message: 'ゴミ袋は、役目を終えたものを包み、次の余白を作る道具です。',
      action: '小さな不要物を一つ手放し、空いた場所を眺めましょう。',
      question: '今日、私が空きを作るために手放せるものは何ですか。',
      gratitude: '終わったものを引き受け、余白を作ってくれてありがとう。',
      image: 'images/oracle/item_017.png'
    },
    {
      id: 'item_018',
      shuku: '箕宿',
      type: '豊かさ循環タイプ',
      cardName: 'ほうきのカード',
      item: 'ほうき',
      keyword: '流れを掃き清める',
      message: 'ほうきは、目に見える場所を整えながら、心の流れも軽くしてくれます。',
      action: '床や玄関を少し掃き、今日入ってきてほしい流れを思い浮かべましょう。',
      question: '今の私の場所に、どんな流れを迎え入れたいですか。',
      gratitude: '空間と心の流れを整えてくれてありがとう。',
      image: 'images/oracle/item_018.png'
    },
    {
      id: 'item_019',
      shuku: '斗宿',
      type: '導きの月タイプ',
      cardName: '時計のカード',
      item: '時計',
      keyword: '時を味方にする',
      message: '時計は、急かすためではなく、今の一歩にふさわしい時を知らせる道具です。',
      action: '時計を見て、今日のための三分だけを自分に渡しましょう。',
      question: '今日、私はどの時間を自分のために使いますか。',
      gratitude: '大切なタイミングを知らせてくれてありがとう。',
      image: 'images/oracle/item_019.png'
    },
    {
      id: 'item_020',
      shuku: '女宿',
      type: '癒しの月タイプ',
      cardName: 'ハンカチのカード',
      item: 'ハンカチ',
      keyword: '品よく整える',
      message: 'ハンカチは、汗や涙をそっと整え、外側と内側の品を守る道具です。',
      action: 'ハンカチを畳み直し、今日の自分を丁寧に扱う一場面を決めましょう。',
      question: '今日、私は自分をどんなふうに丁寧に扱いたいですか。',
      gratitude: '私の小さな乱れを整えてくれてありがとう。',
      image: 'images/oracle/item_020.png'
    },
    {
      id: 'item_021',
      shuku: '虚宿',
      type: '豊かさ循環タイプ',
      cardName: 'クッションのカード',
      item: 'クッション',
      keyword: '受け止める居場所',
      message: 'クッションは、力を抜いて戻れる場所を思い出させてくれます。',
      action: 'クッションを整え、背中や腰をゆるめる時間を一分だけ取りましょう。',
      question: '今の私が安心して戻れる場所はどこですか。',
      gratitude: '私の重さを受け止めてくれてありがとう。',
      image: 'images/oracle/item_021.png'
    },
    {
      id: 'item_022',
      shuku: '危宿',
      type: '変容の月タイプ',
      cardName: '傘のカード',
      item: '傘',
      keyword: '境界を守る',
      message: '傘は、外から降ってくるものと自分の間に、やさしい境界を作る道具です。',
      action: '傘や雨具を整え、今日守りたい自分の境界を一つ書きましょう。',
      question: '今の私が、やさしく守りたい境界は何ですか。',
      gratitude: '私を外の流れから守ってくれてありがとう。',
      image: 'images/oracle/item_022.png'
    },
    {
      id: 'item_023',
      shuku: '室宿',
      type: '導きの月タイプ',
      cardName: '玄関マットのカード',
      item: '玄関マット',
      keyword: '運を迎える入口',
      message: '玄関マットは、外から入る流れを受け止め、家の入口を整える道具です。',
      action: '玄関まわりを一つ整え、今日迎え入れたい運を言葉にしましょう。',
      question: '今日、私はどんな流れを迎え入れたいですか。',
      gratitude: '家と私の入口を整えてくれてありがとう。',
      image: 'images/oracle/item_023.png'
    },
    {
      id: 'item_024',
      shuku: '壁宿',
      type: '癒しの月タイプ',
      cardName: 'ブランケットのカード',
      item: 'ブランケット',
      keyword: '安心に包まれる',
      message: 'ブランケットは、冷えた心身を包み、安心へ戻る時間をくれます。',
      action: '肩や膝にブランケットをかけ、深呼吸を三回しましょう。',
      question: '今日の私が包んであげたい気持ちは何ですか。',
      gratitude: '私をあたたかく包んでくれてありがとう。',
      image: 'images/oracle/item_024.png'
    },
    {
      id: 'item_025',
      shuku: '奎宿',
      type: '表現の月タイプ',
      cardName: 'ノートのカード',
      item: 'ノート',
      keyword: '物語を残す',
      message: 'ノートは、散らばった思いを受け止め、あなたの物語へ育てる場所です。',
      action: 'ノートに今日の気づきを一行だけ書き、日付を添えましょう。',
      question: '今日の私の物語に残したい一文は何ですか。',
      gratitude: '私の言葉を物語として残してくれてありがとう。',
      image: 'images/oracle/item_025.png'
    },
    {
      id: 'item_026',
      shuku: '婁宿',
      type: '豊かさ循環タイプ',
      cardName: 'エプロンのカード',
      item: 'エプロン',
      keyword: '暮らしを育てる',
      message: 'エプロンは、暮らしの手仕事を守り、日常を豊かに育てる道具です。',
      action: '台所や作業場で一つ整え、今日の暮らしに感謝を向けましょう。',
      question: '今日、私の暮らしを支えてくれているものは何ですか。',
      gratitude: '暮らしを育てる手を守ってくれてありがとう。',
      image: 'images/oracle/item_026.png'
    },
    {
      id: 'item_027',
      shuku: '胃宿',
      type: '豊かさ循環タイプ',
      cardName: 'お箸のカード',
      item: 'お箸',
      keyword: 'いただく力',
      message: 'お箸は、命と恵みを日常の中で受け取るための道具です。',
      action: '食事の前にお箸をそろえ、「いただきます」を丁寧に言いましょう。',
      question: '今日、私はどんな恵みを受け取っていますか。',
      gratitude: '命の恵みを運んでくれてありがとう。',
      image: 'images/oracle/item_027.png'
    }
  ];
})();
